name = "nonogram"
# SvelteKit이 빌드한 Worker entry-point
main = ".svelte-kit/cloudflare/_worker.js"
# Workers 런타임 호환성 날짜
compatibility_date = "2025-05-05"
# Node.js 내장 API(예: async_hooks) 사용을 허용하려면 추가
compatibility_flags = ["nodejs_compat"]

routes = [
    { pattern = "nonogram.xiyo.dev", custom_domain = true }
]

# 정적 파일(assets) 바인딩 설정
[assets]
binding   = "ASSETS"                # 코드 내에서 platform.env.ASSETS 로 접근
directory = ".svelte-kit/cloudflare"  # 빌드된 client 파일 위치

